import { Pool, type PoolClient, type QueryResultRow } from '@neondatabase/serverless';

type SqlValue = string | number | boolean | Date | null;

type GlobalDatabase = typeof globalThis & {
  neonPool?: Pool;
  neonSchemaPromise?: Promise<void>;
};

const globalForDb = globalThis as GlobalDatabase;

function getPool() {
  if (globalForDb.neonPool) return globalForDb.neonPool;

  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('Falta la variable de entorno DATABASE_URL para conectar con Neon.');
  }

  globalForDb.neonPool = new Pool({ connectionString });
  return globalForDb.neonPool;
}

export async function query<T extends QueryResultRow = QueryResultRow>(
  text: string,
  values: SqlValue[] = []
): Promise<T[]> {
  const result = await getPool().query<T>(text, values);
  return result.rows;
}

export async function transaction<T>(callback: (client: PoolClient) => Promise<T>): Promise<T> {
  const client = await getPool().connect();
  try {
    await client.query('BEGIN');
    const result = await callback(client);
    await client.query('COMMIT');
    return result;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

/** Creates missing tables only; existing Neon data is never seeded or deleted. */
export function ensureDatabase(): Promise<void> {
  if (!globalForDb.neonSchemaPromise) {
    globalForDb.neonSchemaPromise = createSchema();
  }
  return globalForDb.neonSchemaPromise;
}

async function createSchema() {
  const statements = [
    `CREATE TABLE IF NOT EXISTS categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      icon TEXT DEFAULT 'Utensils',
      display_order INTEGER DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category_id INTEGER NOT NULL REFERENCES categories(id),
      name TEXT NOT NULL,
      description TEXT,
      price DOUBLE PRECISION NOT NULL,
      unit_type TEXT NOT NULL CHECK(unit_type IN ('unidad', 'kilo', 'porcion')),
      available INTEGER NOT NULL DEFAULT 1 CHECK(available IN (0, 1)),
      image_url TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS cash_shifts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      closed_at TIMESTAMPTZ,
      initial_cash DOUBLE PRECISION NOT NULL DEFAULT 0,
      final_cash_expected DOUBLE PRECISION,
      final_cash_counted DOUBLE PRECISION,
      notes TEXT,
      status TEXT NOT NULL DEFAULT 'abierta' CHECK(status IN ('abierta', 'cerrada'))
    )`,
    `CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_number INTEGER NOT NULL,
      order_type TEXT NOT NULL CHECK(order_type IN ('mostrador', 'delivery', 'retiro')),
      customer_name TEXT,
      customer_phone TEXT,
      delivery_address TEXT,
      delivery_notes TEXT,
      payment_method TEXT NOT NULL CHECK(payment_method IN ('efectivo', 'mercadopago', 'tarjeta', 'combinado')),
      payment_status TEXT NOT NULL DEFAULT 'pendiente' CHECK(payment_status IN ('pendiente', 'pagado')),
      kitchen_status TEXT NOT NULL DEFAULT 'pendiente' CHECK(kitchen_status IN ('pendiente', 'en_preparacion', 'listo', 'entregado', 'cancelado')),
      total_amount DOUBLE PRECISION NOT NULL,
      cash_paid DOUBLE PRECISION DEFAULT 0,
      change_amount DOUBLE PRECISION DEFAULT 0,
      notes TEXT,
      cash_shift_id INTEGER REFERENCES cash_shifts(id),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS order_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      product_id INTEGER REFERENCES products(id),
      product_name TEXT NOT NULL,
      unit_price DOUBLE PRECISION NOT NULL,
      quantity DOUBLE PRECISION NOT NULL,
      unit_type TEXT NOT NULL,
      subtotal DOUBLE PRECISION NOT NULL,
      notes TEXT
    )`,
    `CREATE TABLE IF NOT EXISTS cash_movements (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cash_shift_id INTEGER NOT NULL REFERENCES cash_shifts(id),
      type TEXT NOT NULL CHECK(type IN ('ingreso', 'egreso')),
      amount DOUBLE PRECISION NOT NULL,
      concept TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    'ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT',
    'CREATE INDEX IF NOT EXISTS products_category_id_idx ON products(category_id)',
    'CREATE INDEX IF NOT EXISTS orders_created_at_idx ON orders(created_at)',
    'CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items(order_id)',
  ];

  for (const statement of statements) {
    await query(statement);
  }
}
